# Generated by Django 4.2 on 2023-05-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_company_address_remove_company_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
    ]
