# Generated by Django 3.2.6 on 2023-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230504_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vacancies',
            field=models.ManyToManyField(to='api.Vacancy'),
        ),
    ]
