# Generated by Django 3.2.6 on 2023-05-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userandvacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userandvacancy',
            options={'verbose_name': 'Actions'},
        ),
    ]
